# Generated by Django 5.1.5 on 2025-03-30 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_page', '0001_initial'),
        ('table_page', '0003_alter_album_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='form_page.authormodel'),
        ),
    ]
