# Generated by Django 5.1.5 on 2025-03-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=100)),
                ('taskdescription', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('task_assign', models.DateField()),
            ],
        ),
    ]

