# Generated by Django 5.1.5 on 2025-03-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_add_category_task'),
        ('task', '0002_rename_task_assign_addtask_task_assign_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='categories',
            field=models.ManyToManyField(to='category.add_category'),
        ),
    ]
