# Generated by Django 5.1.5 on 2025-02-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('phn_number', models.CharField(max_length=12)),
                ('Instrument_type', models.CharField(max_length=20)),
            ],
        ),
    ]
