# Generated by Django 5.1.5 on 2025-03-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_category',
            name='Task',
        ),
    ]
